clf;
g=Geomatplot;
Point('A',[0 0]);
Point('B',[1 1]);
Point('C',[0.5 1]);
Segment({'A','B'});
Segment({'C','B'});
AngleBisector({'A','B','C'});
bt = @(t,b0,b1,b2) b0.*(1-t).^2 + 2*b1.*(1-t).*t + b2.*t.^2;
Curve(bt,{'A','B','C'});